# Generated by Django 5.1.4 on 2024-12-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("back_api", "0003_product_applications_product_benefits_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
